### ISSUE TITLE
Repository does not have a license

### ISSUE THREAD

**Issue by yarwelp** [Mcgode/City-life-simulator#1]
Hello, I saw your post in /r/TheHappieMakers. It seems like an interesting project. Since part of your goal is to share with others, I think you should apply the terms of an open source license to your code.

I encourage you to consider picking the ISC license, a permissive free software license functionally equivalent to the simplified BSD and the MIT licenses, differing in its removal of language deemed unnecessary following the global adoption of the Berne Convention.

In case you decide to use the ISC license, you can find a copy of the license here: [ISC license](https://gist.githubusercontent.com/eriknstr/84c5c986607f3e4245991480a40e2c45/raw/d998764c0e914964a380b74b28332ea0c7ca28e7/LICENSE).

In order to apply the ISC license from above to your code, create a text file named `LICENSE` or `LICENSE.txt` in the root of your source code and copy [the text of the license](https://gist.githubusercontent.com/eriknstr/84c5c986607f3e4245991480a40e2c45/raw/d998764c0e914964a380b74b28332ea0c7ca28e7/LICENSE) into the file. Replace "YYYY" with the current year, "John Doe" with your own full name, and "john.doe@example.com" with your own e-mail address with the brackets around it intact. The purpose of including your e-mail address is that it lets people know how to contact you if they want to get in touch for some reason. If you don't feel comfortable including your e-mail address, you can remove the &lt;john.doe@example.com&gt; part altogether and not put anything there.

**Comment by Mcgode** [comment]
Yes, forgot to do so. Thanks. Just added it.
